### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Jeroen-G** [tightenco/quicksand#11]
Would it be within the scope of this package if it also deletes Laravel database notifications that are read and X days old?

**Comment by roballport** [comment]
Personally I'd say it's out of scope. For myself, this package is very good because it has a single goal and doesn't try to do too much.

If you have some form of messaging system and need to delete old/read messages then you'd implement your own logic to soft delete those. Quicksand would then force delete your old soft deletes.

I guess it may be helpful in some situations if the package fired off choice events in a similar way Laravel's Auth system does i.e. [https://laravel.com/docs/5.4/authentication#events](https://laravel.com/docs/5.4/authentication#events). However, that may be a little over the top and unnecessary.
